todo_list/base/urls.py
from django.urls import path
from .views import TaskList,TaskDetail,TaskCreate,TaskUpdate,TaskDelete,CustomLoginView,RegisterPage
from django.contrib.auth.views import LogoutView


app_name = 'tasks'

urlpatterns = [
    path('',TaskList.as_view(),name='tasks'),
    path('register/',RegisterPage.as_view(),name='register'),
    path('login/',CustomLoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(next_page = 'tasks:login' ),name='logout'),
    path('task-create/',TaskCreate.as_view(),name='task-create'),
    path('task-update/<int:pk>/',TaskUpdate.as_view(),name='task-update'),
    path('task-delete/<int:pk>/',TaskDelete.as_view(),name='task-delete'),
    path('<int:pk>/',TaskDetail.as_view(),name='task'),
]

todo_list/todo_list/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('tasks/',include('base.urls')),
    path("admin/", admin.site.urls),
]

todo_list/base/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    complete = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering =['complete']

todo_list/base/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render,redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView,FormView
from django.http import HttpRequest, HttpResponse
from .models import Task
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
# LoginRequiredMixin 強制用戶訪問某試圖前需要先登入，如未登入會導向登入頁面
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login



# Class-based views

class CustomLoginView(LoginView):
    template_name = 'base/login.html'
    fields = '__all__'
    redirect_authenticated_user = True
    next_page = reverse_lazy('tasks:tasks')
    # def get_success_url(self):
    #     return reverse_lazy('tasks:tasks')


class RegisterPage(FormView):
    template_name = 'base/register.html'
    form_class =UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('tasks:tasks')
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            # 從表單中獲取了用戶對象，把其保存到了用戶變數中，然後使用了這個變數來進行登錄
            login(self.request,user)
        return super(RegisterPage,self).form_valid(form)
    
    def get(self, *args, **kwargs):
        # 當前用戶已登入的話，重定向到任務頁面
        if self.request.user.is_authenticated:
            return redirect('tasks:tasks')
        # 用戶沒有登錄，將會執行RegisterPage的父類別(即FormView)之get方法，會渲染註冊頁面並傳回給用戶
        return super(RegisterPage,self).get( *args, **kwargs)


class TaskList(LoginRequiredMixin,ListView):
    model = Task
    # queryset 
    context_object_name = 'tasks'

    # def get_queryset(self):
    #     # 過濾 queryset 以過濾出和當前用戶相關的任務
    #     queryset = super().get_queryset()
    #     return queryset.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()

        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            #保留標題以該搜尋關鍵字開頭的任務
            context['tasks'] = context['tasks'].filter(
                title__startswith =search_input
            )
        context['search-input'] = search_input
        return context # 篩選後的任務列表、未完成任務的數量以及搜尋關鍵字

class TaskDetail(LoginRequiredMixin,DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'base/task.html'

class TaskCreate(LoginRequiredMixin,CreateView):
    model = Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('tasks:tasks')
    # 處理表單驗證成功情況
    def form_valid(self, form):
        # 將表單實例的用戶欄位設定為目前請求的用戶
        form.instance.user = self.request.user
        # 獲取TaskCreate類別的父類別（即CreateView）的form_valid()方法
        # 確定在表單驗證成功時，父類別中定義的預設行為也能得以執行。
        return super(TaskCreate,self).form_valid(form)
    

class TaskUpdate(LoginRequiredMixin,UpdateView):
    model = Task
    fields = ['title','description','complete']
    success_url = reverse_lazy('tasks:tasks')

class TaskDelete(LoginRequiredMixin,DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('tasks:tasks')

todo_list/base/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200..1000;1,200..1000&display=swap" rel="stylesheet">
    <style>
        body{
            background-color: #fafafa;
            font-family: "Nunito", sans-serif;
            padding-top: 50px;
        }
        a{
            text-decoration: none;
        }
        .container{
            max-width: 550px;
            margin: auto;
            background-color: #fff;
            -webkit-box-shadow:2px 2px 13px -4px black;
            box-shadow:2px 2px 13px -4px black; ;
        }
        h1,h2,h3,h4,h5,h6{
            font-family: "Raleway", sans-serif;
        }
        .header-bar{
            display: flex;
            justify-content: space-between;
            color:#fff;
            padding: 10px;
            border-radius: 5px 5px 0 0 ;
            background-color: #eea390;
            
        }
        .header-bar a{
            text-decoration: none;
            color:#fff;
        }
        .task-wrapper{
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 20px;
            background-color: #fff;
            border-top: 1px solid rgb(226,226,226);
        }
        .task-title{
            display: flex;
        }
        .task-title a{
            text-decoration: none;
            color: grey;
            margin-left: 10px;
        }
        .task-complete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(146, 199, 66);
            border-radius: 50%;
        }
        .task-incomplete-icon{
            height: 20px;
            width: 20px;
            background-color: rgb(239, 241, 234);
            border-radius: 50%;
        }
        .delete-link{
            text-decoration: none;
            font-weight: 900;
            color: rgb(206, 28, 28);
            font-size: 22px;
            line-height: 0;
        }
        #search-add-wrapper{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }
        #add-link{
            color: #eb796f;
            text-decoration: none;
            font-size: 42px;
            text-shadow: 1px 1px #81313b;
        }
        input[type=text],
        input[type=password],
        textarea{
            border: 1px solid salmon;
            border-radius: 5px;
            padding: 10px;
            width: 95%;
        }
        
        label{
            padding-top: 10px !important;
            display: block;
        }
        .button{
            border: 1px solid salmon;
            background-color: #fafafa;
            color: salmon;
            padding: 10px;
            font-size: 14px;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
        }
        .card-body{
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

</body>
</html>

todo_list/base/templates/base/login.html
{% extends 'base/base.html' %}
{% block content %}

<div class="header-bar">
    <h1>Login</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Login">
    </form>
    <p>Don't have an account? <a href="{% url 'tasks:register' %}" style="color: rgb(169, 162, 162);">Register</a></p>
</div>

{% endblock content %}

todo_list/base/templates/base/register.html
{% extends 'base/base.html' %}
{% block content %}
<div class="header-bar">
    <h1>Register</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}
        <label>{{form.password1.label}}</label>
        {{form.password1}}
        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input class="button" type="submit" value="Register" style="margin-top: 10px;">
    </form>
    <p>Already have an account? <a href="{% url 'tasks:login' %}" style="color: rgb(169, 162, 162);">Login</a></p>
</div>

{% endblock content %}

todo_list/base/templates/base/task.html
{% extends 'base/base.html' %}
{% block content %}
<h1>Task:{{task}}</h1>
{% endblock content %}

todo_list/base/templates/base/task_confirm_delete.html
{% extends 'base/base.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'tasks:tasks' %}">&#8592;Go Back</a>
</div>
<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ task }}"?</p>
        <input class="button" type="submit" value="Delete">
    </form>
</div>

{% endblock content %}

todo_list/base/templates/base/task_form.html
{% extends 'base/base.html' %}
{% block content %}
<div class="header-bar">
    <a href="{% url 'tasks:tasks' %}">&#8592;Back</a>
</div>

<div class="card-body">
    <h3>Create Task</h3>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="submit">
    </form>
</div>

{% endblock content %}

todo_list/base/templates/base/task_list.html
{% extends 'base/base.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Hello,{{request.user|title}}</h1>
        <h3 style="margin: 0;"> you have <i>{{count}}</i> incomplate task{{count |pluralize:'s'}} </h3>
    </div>
    {% if request.user.is_authenticated %}
    <form action="{% url 'tasks:logout' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="button">Logout</button>
    </form>
    {% else %}
    <a href="{% url 'tasks:login' %}">Login</a>
    {% endif %}
</div>


<h1>MY TODO LIST</h1>

<div id="search-add-wrapper">
    <form method="GET" style="margin-top: 20px;display: flex;">
        <input type="text" name="search-area" value="{{search_input}}">
        <input class="button" type="submit" value="Search">
    </form>
    <a id="add-link" href="{% url 'tasks:task-create' %}">&#x2b;</a>
</div>



<div class="task-items-wrapper">
    {% for task in tasks %}
        <div class="task-wrapper">
            {% if task.complete %}
                <div class="task-title">
                    <div class="task-complete-icon"></div>
                    <i><s><a href="{% url 'tasks:task-update' task.id %}">{{task}}</a></s></i>
                </div>
                <a class="delete-link" href="{% url 'tasks:task-delete' task.id %}">&#215;</a>
            {% else %}
                <div class="task-title">
                    <div class="task-incomplete-icon"></div>
                    <a href="{% url 'tasks:task-update' task.id %}">{{task}}</a>
                </div>
                <a class="delete-link" href="{% url 'tasks:task-delete' task.id %}">&#215;</a>
            {% endif %}
            
        </div>
    {% empty %}
    <h3>NO ITEMS IN LIST</h3>
    {% endfor %}
</div>
{% endblock content %}